import assert from "node:assert/strict";
import test from "node:test";

import { buildDashboardQuestBoard } from "../server/services/build-dashboard-quest-board.ts";

const baseUserState = {
  userId: "user-1",
  level: 4,
  totalXp: 520,
  currentStreak: 4,
  weeklyXp: 180,
  starterPathComplete: true,
  rewardEligible: false,
  walletLinked: true,
  walletAgeDays: 7,
  trustScoreBand: "medium" as const,
  subscriptionTier: "free" as const,
  connectedSocials: ["X", "Telegram"],
  successfulReferralCount: 1,
  monthlyPremiumReferralCount: 0,
  annualPremiumReferralCount: 0,
  connectedSocialCount: 2,
  approvedQuestCount: 4,
  starterQuestCount: 3,
  wellnessQuestCount: 1,
  socialQuestCount: 2,
  completedQuestSlugs: ["create-emorya-account"],
  ambassadorCandidate: false,
  ambassadorActive: false,
  campaignSource: "zealy" as const,
};

test("buildDashboardQuestBoard returns a mixed active board with locked previews", () => {
  const quests = [
    {
      id: "starter-1",
      slug: "create-emorya-account",
      title: "Welcome setup",
      description: "Starter",
      category: "app" as const,
      xp_reward: 30,
      difficulty: "easy" as const,
      verification_type: "link-visit" as const,
      required_level: 1,
      required_tier: "free" as const,
      is_premium_preview: false,
      recurrence: "one-time" as const,
      metadata: { track: "starter", targetUrl: "https://example.com" },
      completion_status: null,
    },
    {
      id: "daily-1",
      slug: "play-emoryan-adventure-game",
      title: "Adventure game",
      description: "Daily",
      category: "app" as const,
      xp_reward: 28,
      difficulty: "easy" as const,
      verification_type: "link-visit" as const,
      required_level: 1,
      required_tier: "free" as const,
      is_premium_preview: false,
      recurrence: "daily" as const,
      metadata: { track: "daily", targetUrl: "https://example.com" },
      completion_status: null,
    },
    {
      id: "social-1",
      slug: "share-the-movement-reset",
      title: "Share your Emorya progress",
      description: "Social",
      category: "social" as const,
      xp_reward: 30,
      difficulty: "easy" as const,
      verification_type: "social-oauth" as const,
      required_level: 1,
      required_tier: "free" as const,
      is_premium_preview: false,
      recurrence: "daily" as const,
      metadata: { track: "social" },
      completion_status: null,
    },
    {
      id: "wallet-1",
      slug: "wallet-track",
      title: "Wallet track",
      description: "Wallet",
      category: "staking" as const,
      xp_reward: 75,
      difficulty: "medium" as const,
      verification_type: "wallet-check" as const,
      required_level: 4,
      required_tier: "free" as const,
      is_premium_preview: false,
      recurrence: "weekly" as const,
      metadata: { track: "wallet", unlockRules: { all: [{ type: "wallet_linked", value: true }] } },
      completion_status: null,
    },
    {
      id: "referral-1",
      slug: "three-friend-momentum-push",
      title: "Referral push",
      description: "Referral",
      category: "referral" as const,
      xp_reward: 95,
      difficulty: "medium" as const,
      verification_type: "link-visit" as const,
      required_level: 4,
      required_tier: "free" as const,
      is_premium_preview: false,
      recurrence: "weekly" as const,
      metadata: { track: "referral", unlockRules: { all: [{ type: "successful_referrals", value: 1 }] } },
      completion_status: null,
    },
    {
      id: "campaign-zealy",
      slug: "zealy-bridge-sprint",
      title: "Zealy bridge",
      description: "Campaign",
      category: "limited" as const,
      xp_reward: 85,
      difficulty: "easy" as const,
      verification_type: "link-visit" as const,
      required_level: 3,
      required_tier: "free" as const,
      is_premium_preview: false,
      recurrence: "weekly" as const,
      metadata: { track: "campaign", unlockRules: { all: [{ type: "campaign_source", value: "zealy" }] } },
      completion_status: null,
    },
    {
      id: "premium-locked",
      slug: "monthly-momentum-sprint",
      title: "Premium locked",
      description: "Premium",
      category: "limited" as const,
      xp_reward: 110,
      difficulty: "medium" as const,
      verification_type: "link-visit" as const,
      required_level: 5,
      required_tier: "monthly" as const,
      is_premium_preview: true,
      recurrence: "weekly" as const,
      metadata: { track: "premium" },
      completion_status: null,
    },
  ];

  const board = buildDashboardQuestBoard({
    quests,
    userProgressState: baseUserState,
    journeyState: "activated_free",
  });

  assert.ok(board.some((quest) => quest.track === "wallet"));
  assert.ok(board.some((quest) => quest.track === "campaign"));
  assert.ok(board.some((quest) => quest.status === "locked" && quest.track === "premium"));
});
