ALTER TABLE referrals
ADD COLUMN IF NOT EXISTS signup_reward_xp INTEGER NOT NULL DEFAULT 0;

ALTER TABLE referrals
ADD COLUMN IF NOT EXISTS conversion_reward_xp INTEGER NOT NULL DEFAULT 0;

ALTER TABLE referrals
ADD COLUMN IF NOT EXISTS signup_rewarded_at TIMESTAMPTZ;

ALTER TABLE referrals
ADD COLUMN IF NOT EXISTS conversion_rewarded_at TIMESTAMPTZ;
