UPDATE quest_definitions
SET
  slug = 'convert-2000-calories-to-emrs',
  title = 'Convert 2,000 calories to EMRS in the app',
  description = 'Upload calorie burn target completion screenshot.',
  category = 'app',
  xp_reward = 150,
  difficulty = 'medium',
  verification_type = 'manual-review',
  recurrence = 'monthly',
  required_tier = 'free',
  required_level = 6,
  is_premium_preview = FALSE,
  is_active = TRUE,
  metadata = '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":6}]},"submissionGuidance":{"evidence":["calorie burn target completion screenshot"]},"rewardConfig":{"xp":{"base":150,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":40}},"challengeConfig":{"monthlyCompletionLimit":1,"calorieTarget":2000}}'::jsonb,
  updated_at = NOW()
WHERE id = 'e62bc5b8-3280-4d18-b2fd-a1524c21b453'
   OR slug = 'log-8000-steps';

INSERT INTO quest_definitions (
  id,
  slug,
  title,
  description,
  category,
  xp_reward,
  difficulty,
  verification_type,
  recurrence,
  required_tier,
  required_level,
  is_premium_preview,
  is_active,
  metadata
) VALUES
  (
    '6ce4bfe0-aefc-4685-921e-9ec5554216b1',
    '500-in-24',
    '500 in 24',
    'Convert 500 calories to EMRS in one day. Timestamped start and finish screenshots for evidence.',
    'app',
    100,
    'easy',
    'manual-review',
    'weekly',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":3}]},"submissionGuidance":{"evidence":["timestamped start screenshot","timestamped finish screenshot"]},"rewardConfig":{"xp":{"base":100,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":22}},"challengeConfig":{"dailyCalorieTarget":500,"windowHours":24,"maxCompletionsPerWindow":1}}'::jsonb
  ),
  (
    '7d78d0ea-1988-4cd4-9726-df0cbfd283ff',
    'weekly-warrior',
    'Weekly Warrior',
    '500 calories to EMRS burns for 7 consecutive days. Timestamped start and finish screenshots for evidence.',
    'app',
    400,
    'hard',
    'manual-review',
    'weekly',
    'free',
    5,
    FALSE,
    TRUE,
    '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":5}]},"submissionGuidance":{"evidence":["timestamped start screenshot","timestamped finish screenshot"]},"rewardConfig":{"xp":{"base":400,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":75}},"challengeConfig":{"dailyCalorieTarget":500,"consecutiveDays":7}}'::jsonb
  ),
  (
    'db1db3b7-6103-4f05-aa97-904a3fd4e6d2',
    'emorya-marathon',
    'Emorya Marathon',
    '500 calories a day for 30 days. Complete all 30 daily burns to unlock the full marathon reward run.',
    'app',
    3000,
    'hard',
    'manual-review',
    'one-time',
    'free',
    8,
    FALSE,
    TRUE,
    '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":8}]},"submissionGuidance":{"evidence":["daily calorie burn screenshot"]},"rewardConfig":{"xp":{"base":3000,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":160},"milestoneRewards":{"count":30,"cadence":"daily"}},"challengeConfig":{"dailyCalorieTarget":500,"durationDays":30,"dailyCheckpoints":30}}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  xp_reward = EXCLUDED.xp_reward,
  difficulty = EXCLUDED.difficulty,
  verification_type = EXCLUDED.verification_type,
  recurrence = EXCLUDED.recurrence,
  required_tier = EXCLUDED.required_tier,
  required_level = EXCLUDED.required_level,
  is_premium_preview = EXCLUDED.is_premium_preview,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
