INSERT INTO quest_definitions (
  id,
  slug,
  title,
  description,
  category,
  xp_reward,
  difficulty,
  verification_type,
  recurrence,
  required_tier,
  required_level,
  is_premium_preview,
  is_active,
  metadata
) VALUES
  (
    '9d955d0c-a8cf-45d0-b5a2-e28f5de26468',
    'submit-your-referral-story',
    'Submit your referral story',
    'Write a short explanation of who you referred, why they were a fit for Emorya, and what happened next.',
    'referral',
    95,
    'medium',
    'text-submission',
    'monthly',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"referral","platformLabel":"Referral","proofType":"text","proofInstructions":"Explain who you referred, why they were a strong fit, and whether they activated.","unlockRules":{"all":[{"type":"min_level","value":3}]},"rewardConfig":{"xp":{"base":95,"premiumMultiplierEligible":true},"tokenEffect":"none"},"previewConfig":{"label":"Referral story"}}'::jsonb
  ),
  (
    '86caa40f-3578-4e7b-9660-5a60d462f65f',
    'share-your-emorya-testimonial',
    'Share your Emorya testimonial',
    'Write a short testimonial about your Emorya experience, what has helped, and why you keep using it.',
    'social',
    110,
    'medium',
    'text-submission',
    'monthly',
    'free',
    4,
    FALSE,
    TRUE,
    '{"track":"social","platformLabel":"Testimonial","proofType":"text","proofInstructions":"Write a genuine short testimonial. Add an optional public reference link if you shared it elsewhere.","unlockRules":{"all":[{"type":"min_level","value":4}]},"rewardConfig":{"xp":{"base":110,"premiumMultiplierEligible":true},"tokenEffect":"none"},"previewConfig":{"label":"Testimonial trust signal"}}'::jsonb
  ),
  (
    'fd48b1a4-68e7-490b-9a98-18b3115edec4',
    'explain-your-calorie-to-emrs-journey',
    'Explain your calorie-to-EMRS journey',
    'Write a clear summary of how your calorie activity connects to EMRS progression and what that means to you.',
    'learn',
    125,
    'medium',
    'text-submission',
    'monthly',
    'free',
    5,
    FALSE,
    TRUE,
    '{"track":"learn","platformLabel":"EMRS journey","proofType":"text","proofInstructions":"Summarize how calorie conversion connects to EMRS and rewards in your own words.","unlockRules":{"all":[{"type":"min_level","value":5}]},"rewardConfig":{"xp":{"base":125,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":18}},"previewConfig":{"label":"Reward understanding"}}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  xp_reward = EXCLUDED.xp_reward,
  difficulty = EXCLUDED.difficulty,
  verification_type = EXCLUDED.verification_type,
  recurrence = EXCLUDED.recurrence,
  required_tier = EXCLUDED.required_tier,
  required_level = EXCLUDED.required_level,
  is_premium_preview = EXCLUDED.is_premium_preview,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
