INSERT INTO quest_definitions (
  id,
  slug,
  title,
  description,
  category,
  xp_reward,
  difficulty,
  verification_type,
  recurrence,
  required_tier,
  required_level,
  is_premium_preview,
  is_active,
  metadata
) VALUES
  (
    '1c31bf57-42b4-4788-8d0c-6a8dfb587205',
    'demo-link-visit-check',
    'Admin demo: Link visit check',
    'Open the linked admin demo destination to validate the link-visit lane.',
    'app',
    15,
    'easy',
    'link-visit',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{
      "track":"campaign",
      "platformLabel":"Website",
      "ctaLabel":"Open demo destination",
      "targetUrl":"https://demo.emorya.internal/link-visit",
      "campaignPackId":"admin-verification-demo",
      "campaignPackLabel":"Admin verification demo",
      "previewConfig":{"label":"Link visit lane"}
    }'::jsonb
  ),
  (
    'b3bf5b0d-d3b5-44c7-bf57-1fcb3ef4c16a',
    'demo-manual-review-proof',
    'Admin demo: Manual review proof',
    'Submit a screenshot and note to validate the manual-review lane and task-block evidence capture.',
    'creative',
    40,
    'medium',
    'manual-review',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{
      "track":"creative",
      "platformLabel":"Review queue",
      "ctaLabel":"Open upload brief",
      "targetUrl":"https://demo.emorya.internal/manual-review",
      "proofType":"file-upload",
      "proofInstructions":"Upload one proof file and add a short reviewer note.",
      "campaignPackId":"admin-verification-demo",
      "campaignPackLabel":"Admin verification demo",
      "taskBlocks":[
        {
          "id":"open-brief",
          "label":"Open the demo brief",
          "platformLabel":"Website",
          "ctaLabel":"Open brief",
          "targetUrl":"https://demo.emorya.internal/manual-review",
          "proofType":"link",
          "proofInstructions":"Open the instructions before submitting.",
          "required":true
        },
        {
          "id":"upload-proof",
          "label":"Upload proof and context",
          "description":"Attach a proof file and explain what you completed.",
          "platformLabel":"Review queue",
          "proofType":"file-upload",
          "proofInstructions":"Upload a file and add a note for moderation.",
          "required":true
        }
      ],
      "previewConfig":{"label":"Manual review lane"}
    }'::jsonb
  ),
  (
    'c8688e5c-5631-4942-8942-bd7c52c61f5e',
    'demo-text-submission-brief',
    'Admin demo: Text submission brief',
    'Write a short response to validate the text-submission lane.',
    'learn',
    25,
    'easy',
    'text-submission',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{
      "track":"starter",
      "platformLabel":"Written response",
      "proofType":"text",
      "proofInstructions":"Write a 2-3 sentence answer describing what this lane is good for.",
      "campaignPackId":"admin-verification-demo",
      "campaignPackLabel":"Admin verification demo",
      "previewConfig":{"label":"Text submission lane"}
    }'::jsonb
  ),
  (
    'ca06bfa0-ed59-4c2a-83fc-d83e369b0283',
    'demo-quiz-readiness-check',
    'Admin demo: Quiz readiness check',
    'Answer the short quiz correctly to validate the quiz lane.',
    'learn',
    30,
    'easy',
    'quiz',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{
      "track":"quiz",
      "totalQuestions":3,
      "passScore":2,
      "campaignPackId":"admin-verification-demo",
      "campaignPackLabel":"Admin verification demo",
      "previewConfig":{"label":"Quiz lane"}
    }'::jsonb
  ),
  (
    '82bc2777-cfc4-4264-9654-810bfe4abd4f',
    'demo-wallet-connection-check',
    'Admin demo: Wallet connection check',
    'Verify a linked wallet to validate the wallet-check lane.',
    'app',
    35,
    'easy',
    'wallet-check',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{
      "track":"wallet",
      "platformLabel":"Wallet",
      "proofInstructions":"Pick a linked wallet and submit it for verification.",
      "walletCheckMode":"linked-wallet-ownership",
      "campaignPackId":"admin-verification-demo",
      "campaignPackLabel":"Admin verification demo",
      "previewConfig":{"label":"Wallet-check lane"}
    }'::jsonb
  ),
  (
    '0f2612d6-1652-4d2b-84c9-6b8cdb0fd83f',
    'demo-api-verification-callback',
    'Admin demo: API verification callback',
    'Submit an external reference and resolve it later through the async callback lane.',
    'app',
    45,
    'medium',
    'api-check',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{
      "track":"campaign",
      "platformLabel":"Webhook verifier",
      "ctaLabel":"Open verifier guide",
      "targetUrl":"https://demo.emorya.internal/api-check",
      "proofType":"url",
      "proofInstructions":"Submit an external reference, then resolve it later through the callback endpoint.",
      "apiVerification":{"endpointUrl":"https://demo.emorya.internal/api/verify/demo","method":"POST","failureMode":"pending-review","callbackToken":"demo-callback-token"},
      "campaignPackId":"admin-verification-demo",
      "campaignPackLabel":"Admin verification demo",
      "previewConfig":{"label":"API callback lane"}
    }'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  xp_reward = EXCLUDED.xp_reward,
  difficulty = EXCLUDED.difficulty,
  verification_type = EXCLUDED.verification_type,
  recurrence = EXCLUDED.recurrence,
  required_tier = EXCLUDED.required_tier,
  required_level = EXCLUDED.required_level,
  is_premium_preview = EXCLUDED.is_premium_preview,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
