INSERT INTO users (
  id,
  email,
  password_hash,
  display_name,
  avatar_url,
  attribution_source,
  level,
  total_xp,
  current_streak,
  longest_streak,
  subscription_tier,
  referral_code,
  referred_by,
  created_at
) VALUES
  (
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    'oliver@emorya.com',
    'scrypt:ebb3c86565a214bb0825099169095108:f116fc2e57cd835d1d47022289c1663bdc096468eab4d6149639906218c04d94d6ff773b18a18b7b9c1ab48dbf8b6e9a21d921db368fa278b9435f06d99efbe9',
    'Oliver',
    NULL,
    'zealy',
    8,
    4520,
    14,
    14,
    'free',
    'EMORYA-8W3K9R',
    NULL,
    NOW() - INTERVAL '14 days'
  ),
  (
    '2196480b-b0fc-4e15-8837-e1d02177c7ed',
    'lina@emorya.com',
    'scrypt:d7e07bbf6effc2427264688c379aa587:06e824dab6967fa7cae5d82dc026f16254fc3bcb6d0b5afc758a5dd17e5c559a34ec5703c4d18c54370ae3ac5ffc18b17f45c1643f7133f2d5d6c455031c1281',
    'Lina',
    NULL,
    'social',
    18,
    37140,
    31,
    31,
    'annual',
    'EMORYA-LINA18',
    NULL,
    NOW() - INTERVAL '60 days'
  ),
  (
    '9010db77-a008-4f24-ac2c-af801dca9a6b',
    'kairo@emorya.com',
    NULL,
    'Kairo',
    NULL,
    'referral',
    17,
    35520,
    21,
    24,
    'annual',
    'EMORYA-KAI17',
    NULL,
    NOW() - INTERVAL '52 days'
  ),
  (
    'c657ad58-bf65-4def-8cab-5f2bd4a85dbf',
    'mia@emorya.com',
    NULL,
    'Mia',
    NULL,
    'organic',
    16,
    34100,
    18,
    20,
    'monthly',
    'EMORYA-MIA16',
    NULL,
    NOW() - INTERVAL '46 days'
  ),
  (
    '8cc801df-004b-4e20-a5c1-cf5f0f1f642d',
    'nico@emorya.com',
    NULL,
    'Nico',
    NULL,
    'ads',
    8,
    4485,
    9,
    13,
    'free',
    'EMORYA-NICO08',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    NOW() - INTERVAL '16 days'
  ),
  (
    '2b74bcd9-98e8-455a-bede-d1a5876775fd',
    'aya@emorya.com',
    NULL,
    'Aya',
    NULL,
    'social',
    8,
    4440,
    10,
    12,
    'monthly',
    'EMORYA-AYA08',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    NOW() - INTERVAL '18 days'
  )
ON CONFLICT (id) DO UPDATE SET
  email = EXCLUDED.email,
  password_hash = EXCLUDED.password_hash,
  display_name = EXCLUDED.display_name,
  avatar_url = EXCLUDED.avatar_url,
  attribution_source = EXCLUDED.attribution_source,
  level = EXCLUDED.level,
  total_xp = EXCLUDED.total_xp,
  current_streak = EXCLUDED.current_streak,
  longest_streak = EXCLUDED.longest_streak,
  subscription_tier = EXCLUDED.subscription_tier,
  referral_code = EXCLUDED.referral_code,
  referred_by = EXCLUDED.referred_by;

INSERT INTO user_roles (user_id, role, granted_by) VALUES
  ('6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'super_admin'::app_role, NULL),
  ('6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'admin'::app_role, NULL)
ON CONFLICT (user_id, role) DO NOTHING;

INSERT INTO user_identities (id, user_id, provider, provider_subject, status, created_at) VALUES
  (
    'f62d4e31-b801-4669-bc44-b447acfbf4ce',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    'multiversx',
    'erd1emoryaoliverwallet0000000000000000000000000000000000000',
    'active',
    NOW() - INTERVAL '13 days'
  ),
  (
    '8b0d2cc8-08ab-4465-9aa8-e8f2296c1108',
    '2196480b-b0fc-4e15-8837-e1d02177c7ed',
    'multiversx',
    'erd1emoryalinaannual000000000000000000000000000000000000000',
    'active',
    NOW() - INTERVAL '44 days'
  )
ON CONFLICT (provider, provider_subject) DO NOTHING;

INSERT INTO social_connections (id, user_id, platform, handle, verified, connected_at) VALUES
  ('7bb59c4d-42f4-471d-82f3-8a96a55bcb0f', '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'X', '@oliver_moves', TRUE, NOW() - INTERVAL '13 days'),
  ('118e1e4c-dcbc-428f-bf72-c833f7f28d56', '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'Telegram', 'olivermoves', TRUE, NOW() - INTERVAL '13 days'),
  ('532f5286-1a9b-4102-b8fd-41be8b1140f0', '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'Discord', 'oliver#8402', TRUE, NOW() - INTERVAL '12 days'),
  ('d1d5f3aa-7c67-4b22-ae84-503979c53e5d', '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'TikTok', NULL, FALSE, NULL),
  ('87b9af1d-6efe-4d6d-b05b-37df0911a0d9', '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'Instagram', NULL, FALSE, NULL),
  ('dd617222-d1d8-4c27-a41c-18411d04191f', '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'CoinMarketCap', NULL, FALSE, NULL)
ON CONFLICT (user_id, platform) DO NOTHING;

INSERT INTO quest_definitions (
  id,
  slug,
  title,
  description,
  category,
  xp_reward,
  difficulty,
  verification_type,
  recurrence,
  required_tier,
  required_level,
  is_premium_preview,
  is_active,
  metadata
) VALUES
  (
    '4b93f90c-cd8b-4297-bc7d-6f1ebf5293fa',
    'share-your-verified-progress-screenshot',
    'Share your verified progress screenshot',
    'Post a real Emorya progress screenshot on X and submit the link.',
    'social',
    90,
    'medium',
    'manual-review',
    'weekly',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"social","unlockRules":{"all":[{"type":"min_level","value":3}]},"submissionGuidance":{"evidence":["public post link","progress screenshot"]},"rewardConfig":{"xp":{"base":90,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    '4cbda570-89a7-4c9d-bcdc-3e482ed02ae3',
    'premium-economics-quiz',
    'Premium economics quiz',
    'Finish a 5-question lesson on Premium benefits and annual savings.',
    'learn',
    45,
    'medium',
    'quiz',
    'one-time',
    'free',
    2,
    FALSE,
    FALSE,
    '{"track":"quiz","passScore":4,"totalQuestions":5,"unlockRules":{"all":[{"type":"min_level","value":2}]},"rewardConfig":{"xp":{"base":45,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":16}}}'::jsonb
  ),
  (
    'd19f442f-3b81-454c-aa94-6f33b7524d59',
    'visit-premium-explainer',
    'Visit the premium explainer',
    'Open the premium benefits explainer and confirm the visit.',
    'learn',
    20,
    'easy',
    'link-visit',
    'daily',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"starter","targetUrl":"https://example.com/premium-explainer","unlockRules":{"all":[]},"rewardConfig":{"xp":{"base":20,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    'ca8d9fdd-aa13-4e69-8ae7-615f7a2a0f83',
    'create-emorya-account',
    'Create Emorya account',
    'Create your Emorya account so your quest path, rewards, and calorie journey can begin.',
    'app',
    60,
    'easy',
    'link-visit',
    'one-time',
    'free',
    1,
    FALSE,
    TRUE,
    '{"track":"starter","targetUrl":"https://example.com/create-account","unlockRules":{"all":[]},"rewardConfig":{"xp":{"base":60,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    '5a425a67-b7ab-4bca-9629-a90a507663e5',
    'connect-your-xportal-wallet',
    'Connect your XPortal Wallet',
    'Connect your xPortal wallet so EMRS rewards and calorie-linked progress can settle correctly.',
    'learn',
    80,
    'easy',
    'link-visit',
    'one-time',
    'free',
    2,
    FALSE,
    TRUE,
    '{"track":"wallet","targetUrl":"https://example.com/connect-xportal-wallet","unlockRules":{"all":[{"type":"min_level","value":2}]},"rewardConfig":{"xp":{"base":80,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":18}}}'::jsonb
  ),
  (
    'c90f8fab-a89d-41cc-ad69-73527891e7e2',
    'convert-your-first-calories',
    'Convert your first calories',
    'Complete your first calorie conversion so the EMRS reward loop starts with a verified first win.',
    'app',
    90,
    'easy',
    'manual-review',
    'one-time',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"starter","unlockRules":{"all":[{"type":"min_level","value":3}]},"submissionGuidance":{"evidence":["first calorie conversion screenshot"]},"rewardConfig":{"xp":{"base":90,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":18}},"challengeConfig":{"firstConversion":true}}'::jsonb
  ),
  (
    '7cc727ca-e6eb-4bb1-917d-ef9b6d9bf9bd',
    'play-emoryan-adventure-game',
    'Play Emoryan Adventure Game',
    'Open the Emoryan Adventure Game and complete one run to keep your daily momentum active.',
    'app',
    30,
    'easy',
    'link-visit',
    'daily',
    'free',
    1,
    FALSE,
    TRUE,
    '{"track":"daily","targetUrl":"https://example.com/emoryan-adventure","unlockRules":{"all":[]},"rewardConfig":{"xp":{"base":30,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    'ef257868-6d9d-4fcf-9ce9-3ee1920548e4',
    'complete-daily-wheel-spin',
    'Complete your Daily Wheel Spin',
    'Open the daily wheel and finish one spin to keep your reward rhythm moving.',
    'app',
    35,
    'easy',
    'link-visit',
    'daily',
    'free',
    2,
    FALSE,
    TRUE,
    '{"track":"daily","targetUrl":"https://example.com/daily-wheel","unlockRules":{"all":[{"type":"min_level","value":2}]},"rewardConfig":{"xp":{"base":35,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":10}}}'::jsonb
  ),
  (
    'e62bc5b8-3280-4d18-b2fd-a1524c21b453',
    'convert-2000-calories-to-emrs',
    'Convert 2,000 calories to EMRS in the app',
    'Upload calorie burn target completion screenshot.',
    'app',
    150,
    'medium',
    'manual-review',
    'monthly',
    'free',
    6,
    FALSE,
    TRUE,
    '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":6}]},"submissionGuidance":{"evidence":["calorie burn target completion screenshot"]},"rewardConfig":{"xp":{"base":150,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":40}},"challengeConfig":{"monthlyCompletionLimit":1,"calorieTarget":2000}}'::jsonb
  ),
  (
    '6ce4bfe0-aefc-4685-921e-9ec5554216b1',
    '500-in-24',
    '500 in 24',
    'Convert 500 calories to EMRS in one day. Timestamped start and finish screenshots for evidence.',
    'app',
    100,
    'easy',
    'manual-review',
    'weekly',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":3}]},"submissionGuidance":{"evidence":["timestamped start screenshot","timestamped finish screenshot"]},"rewardConfig":{"xp":{"base":100,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":22}},"challengeConfig":{"dailyCalorieTarget":500,"windowHours":24,"maxCompletionsPerWindow":1}}'::jsonb
  ),
  (
    '7d78d0ea-1988-4cd4-9726-df0cbfd283ff',
    'weekly-warrior',
    'Weekly Warrior',
    '500 calories to EMRS burns for 7 consecutive days. Timestamped start and finish screenshots for evidence.',
    'app',
    400,
    'hard',
    'manual-review',
    'weekly',
    'free',
    5,
    FALSE,
    TRUE,
    '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":5}]},"submissionGuidance":{"evidence":["timestamped start screenshot","timestamped finish screenshot"]},"rewardConfig":{"xp":{"base":400,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":75}},"challengeConfig":{"dailyCalorieTarget":500,"consecutiveDays":7}}'::jsonb
  ),
  (
    '91fd3647-b4bd-4f18-aeb9-fc23254cf4a0',
    'fourteen-day-calorie-streak',
    '14-day calorie streak',
    'Convert 500 calories to EMRS for 14 consecutive days to prove a durable routine.',
    'app',
    900,
    'hard',
    'manual-review',
    'monthly',
    'free',
    7,
    FALSE,
    FALSE,
    '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":7}]},"submissionGuidance":{"evidence":["timestamped start screenshot","timestamped finish screenshot","daily calorie conversion proof"]},"rewardConfig":{"xp":{"base":900,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":110}},"challengeConfig":{"dailyCalorieTarget":500,"consecutiveDays":14}}'::jsonb
  ),
  (
    'db1db3b7-6103-4f05-aa97-904a3fd4e6d2',
    'emorya-marathon',
    'Emorya Marathon',
    '500 calories a day for 30 days. Complete all 30 daily burns to unlock the full marathon reward run.',
    'app',
    3000,
    'hard',
    'manual-review',
    'one-time',
    'free',
    8,
    FALSE,
    TRUE,
    '{"track":"daily","unlockRules":{"all":[{"type":"min_level","value":8}]},"submissionGuidance":{"evidence":["daily calorie burn screenshot"]},"rewardConfig":{"xp":{"base":3000,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":160},"milestoneRewards":{"count":30,"cadence":"daily"}},"challengeConfig":{"dailyCalorieTarget":500,"durationDays":30,"dailyCheckpoints":30}}'::jsonb
  ),
  (
    'df10d884-7c1a-403d-9bd5-aeb4ee7f95a4',
    'complete-the-community-triangle',
    'Complete the community triangle',
    'Visit the X, Telegram, and Discord hubs and clear the social growth trio.',
    'social',
    75,
    'medium',
    'link-visit',
    'weekly',
    'free',
    3,
    FALSE,
    FALSE,
    '{"track":"social","targetUrl":"https://example.com/community-triangle","unlockRules":{"all":[{"type":"connected_social_count","value":1}]},"rewardConfig":{"xp":{"base":75,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":22}}}'::jsonb
  ),
  (
    '3275f8ca-13cd-4297-94fc-f0f45458d225',
    'invite-your-first-accountability-partner',
    'Invite your first accountability partner',
    'Invite one friend to join you on Emorya as an accountability partner.',
    'referral',
    80,
    'easy',
    'link-visit',
    'one-time',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"referral","targetUrl":"https://example.com/accountability-partner","unlockRules":{"all":[{"type":"min_level","value":3}]},"rewardConfig":{"xp":{"base":80,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    '0baa67a0-0d57-42fd-87e5-d77052986842',
    'refer-one-user-who-converts-calories',
    'Refer one user who converts calories',
    'Refer one user who completes their first verified calorie conversion.',
    'referral',
    180,
    'medium',
    'link-visit',
    'monthly',
    'free',
    4,
    FALSE,
    TRUE,
    '{"track":"referral","targetUrl":"https://example.com/referral-conversion","unlockRules":{"all":[{"type":"min_level","value":4},{"type":"successful_referrals","value":1}]},"rewardConfig":{"xp":{"base":180,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":40}}}'::jsonb
  ),
  (
    '379b37d0-8cdd-4e93-95bc-f8b1b5a6afe0',
    'upgrade-to-premium-monthly',
    'Upgrade to Premium Monthly',
    'Unlock Premium Monthly to access stronger rewards, better momentum, and premium-only progression.',
    'limited',
    350,
    'medium',
    'link-visit',
    'one-time',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"premium","targetUrl":"https://example.com/upgrade-monthly","unlockRules":{"all":[{"type":"min_level","value":3},{"type":"starter_path_complete","value":true}]},"rewardConfig":{"xp":{"base":350,"premiumMultiplierEligible":false},"tokenEffect":"token_bonus","tokenBonus":{"multiplier":1.3}}}'::jsonb
  ),
  (
    'b2e73062-4fa1-4ed7-af5c-f5d75c9f1103',
    'zealy-bridge-sprint',
    'Zealy bridge sprint',
    'Convert your Zealy momentum into native Emorya activity by clearing the bridge sprint.',
    'limited',
    85,
    'easy',
    'link-visit',
    'weekly',
    'free',
    3,
    FALSE,
    FALSE,
    '{"track":"campaign","targetUrl":"https://example.com/zealy-bridge","unlockRules":{"all":[{"type":"campaign_source","value":"zealy"}]},"rewardConfig":{"xp":{"base":85,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":18}}}'::jsonb
  ),
  (
    '75d12a7a-c326-4fb5-9af4-fec69f04ccab',
    'galxe-migration-loop',
    'Galxe migration loop',
    'Move a Galxe audience member into the native Emorya habit and wallet loop.',
    'limited',
    90,
    'medium',
    'link-visit',
    'weekly',
    'free',
    3,
    FALSE,
    FALSE,
    '{"track":"campaign","targetUrl":"https://example.com/galxe-bridge","unlockRules":{"all":[{"type":"campaign_source","value":"galxe"}]},"rewardConfig":{"xp":{"base":90,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":18}}}'::jsonb
  ),
  (
    '59a8048b-8c8a-4f7a-b383-a08cf69ee6d4',
    'taskon-conversion-lane',
    'TaskOn conversion lane',
    'Guide a TaskOn entrant from campaign claim behavior into recurring Emorya progress.',
    'limited',
    90,
    'medium',
    'link-visit',
    'weekly',
    'free',
    3,
    FALSE,
    FALSE,
    '{"track":"campaign","targetUrl":"https://example.com/taskon-bridge","unlockRules":{"all":[{"type":"campaign_source","value":"taskon"}]},"rewardConfig":{"xp":{"base":90,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":18}}}'::jsonb
  ),
  (
    '8ec2112e-eebc-48dd-a32c-a2ca6c705c5a',
    'this-weeks-ugc-challenge',
    'This week''s UGC challenge',
    'Create and submit one polished piece of UGC about your Emorya progress, calorie journey, or reward momentum.',
    'creative',
    160,
    'medium',
    'manual-review',
    'weekly',
    'free',
    5,
    FALSE,
    TRUE,
    '{"track":"creative","unlockRules":{"all":[{"type":"min_level","value":5}]},"rewardConfig":{"xp":{"base":160,"premiumMultiplierEligible":true},"tokenEffect":"none"},"cooldownHours":48}'::jsonb
  ),
  (
    '76d48c0e-38b3-4087-8863-68d308ee60b8',
    'strengthen-the-core-30-day-hold',
    'Strengthen the Core: 30-day stake hold',
    'Maintain an EMR staking position for 30 days to unlock a major wallet and trust milestone.',
    'staking',
    420,
    'hard',
    'wallet-check',
    'monthly',
    'monthly',
    9,
    TRUE,
    FALSE,
    '{"track":"wallet","walletCheckMode":"linked-wallet-ownership","requiredWalletPrefix":"erd","unlockRules":{"all":[{"type":"min_level","value":9},{"type":"wallet_linked","value":true},{"type":"subscription_tier","value":"monthly"},{"type":"starter_path_complete","value":true}]},"rewardConfig":{"xp":{"base":420,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":70}},"challengeConfig":{"durationDays":30},"previewConfig":{"label":"Wallet Rewards"}}'::jsonb
  ),
  (
    '9e8dc739-f0d7-4ed5-b3a4-eb3ff7c8b6ed',
    'upgrade-to-annual',
    'Upgrade to Annual',
    'Upgrade to an annual plan to unlock the strongest loyalty rewards, premium access, and annual-only bonus pathways.',
    'limited',
    1200,
    'medium',
    'link-visit',
    'one-time',
    'free',
    5,
    FALSE,
    TRUE,
    '{"track":"premium","targetUrl":"https://example.com/upgrade-annual","unlockRules":{"all":[{"type":"min_level","value":5},{"type":"starter_path_complete","value":true}]},"rewardConfig":{"xp":{"base":1200,"premiumMultiplierEligible":false},"tokenEffect":"direct_token_reward","directTokenReward":{"asset":"EMR","amount":25,"requiresWallet":true}},"annualBonus":{"stakedEmrBase":25,"perConvertedReferral":10}}'::jsonb
  ),
  (
    '0cf45bc5-66d8-46cb-a2aa-d8fcf0c86f03',
    'view-your-emrs-reward-path',
    'View your EMRS reward path',
    'Open your EMRS reward path and review how calorie conversions, streaks, and wallet actions turn into reward eligibility.',
    'learn',
    40,
    'easy',
    'link-visit',
    'one-time',
    'free',
    2,
    FALSE,
    TRUE,
    '{"track":"starter","targetUrl":"https://example.com/emrs-reward-path","unlockRules":{"all":[{"type":"min_level","value":2}]},"rewardConfig":{"xp":{"base":40,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":10}}}'::jsonb
  ),
  (
    '2833c51d-e8f6-49d2-8c38-f4fd032f6af7',
    'signature-creator-brief',
    'Signature creator brief',
    'Publish a multi-post thread or short-form video tagged for the race campaign.',
    'creative',
    240,
    'hard',
    'manual-review',
    'weekly',
    'annual',
    10,
    TRUE,
    FALSE,
    '{"track":"ambassador","timebox":"Ends in 2d 11h","unlockRules":{"all":[{"type":"ambassador_candidate","value":true},{"type":"subscription_tier","value":"annual"}]},"rewardConfig":{"xp":{"base":240,"premiumMultiplierEligible":true},"tokenEffect":"direct_token_reward","directTokenReward":{"asset":"EMR","amount":25,"requiresWallet":true}}}'::jsonb
  ),
  (
    '52b11fa2-0bd4-45cb-b7aa-9d3947a01f34',
    'join-emorya-telegram',
    'Join Emorya Telegram',
    'Join the Emorya Telegram community and submit proof that you''re in.',
    'social',
    20,
    'easy',
    'social-oauth',
    'one-time',
    'free',
    1,
    FALSE,
    TRUE,
    '{"track":"social","targetUrl":"https://example.com/join-telegram","unlockRules":{"all":[]},"rewardConfig":{"xp":{"base":20,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    '42011d57-13d1-4d3c-8cbf-af9db7f693b8',
    'join-emorya-discord',
    'Join Emorya Discord',
    'Join the Emorya Discord server and confirm your entry.',
    'social',
    20,
    'easy',
    'social-oauth',
    'one-time',
    'free',
    1,
    FALSE,
    TRUE,
    '{"track":"social","targetUrl":"https://example.com/join-discord","unlockRules":{"all":[]},"rewardConfig":{"xp":{"base":20,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    '7c8f4788-f2dd-45ad-a150-7f5957d4dd7f',
    'follow-emorya-on-x',
    'Follow Emorya on X',
    'Follow Emorya on X and submit proof of follow.',
    'social',
    20,
    'easy',
    'social-oauth',
    'one-time',
    'free',
    1,
    FALSE,
    TRUE,
    '{"track":"social","targetUrl":"https://example.com/follow-x","unlockRules":{"all":[]},"rewardConfig":{"xp":{"base":20,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    'a96ee831-911f-4e15-86db-e8bbf8eb8a90',
    'like-this-weeks-emorya-post',
    'Like this week''s Emorya post',
    'Like the featured Emorya post for this week and submit the post link.',
    'social',
    15,
    'easy',
    'manual-review',
    'weekly',
    'free',
    1,
    FALSE,
    TRUE,
    '{"track":"social","targetUrl":"https://example.com/weekly-post","unlockRules":{"all":[]},"submissionGuidance":{"evidence":["post link"]},"rewardConfig":{"xp":{"base":15,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    '8738e1e6-18d7-4f6f-85fe-860a4f14b0b1',
    'share-an-emorya-post',
    'Share an Emorya post',
    'Share or repost an Emorya post to your audience and submit proof.',
    'social',
    35,
    'easy',
    'manual-review',
    'weekly',
    'free',
    2,
    FALSE,
    TRUE,
    '{"track":"social","platformLabel":"X","ctaLabel":"Open X task","targetUrl":"https://x.com/emoryaapp","proofType":"url","proofInstructions":"Open the active Emorya post, share or repost it on X, then submit the public post URL for review.","taskBlocks":[{"id":"open-x-thread","label":"Open the active Emorya post","platformLabel":"X","ctaLabel":"Open thread","targetUrl":"https://x.com/emoryaapp/status/example","proofType":"link","proofInstructions":"Open the active X thread before completing the proof step.","required":true},{"id":"submit-share-proof","label":"Submit your shared-post proof","description":"Paste the repost, quote post, or reply link.","platformLabel":"X","proofType":"url","proofInstructions":"Paste the public X URL for review.","required":true}],"unlockRules":{"all":[{"type":"min_level","value":2}]},"submissionGuidance":{"evidence":["shared post link"]},"rewardConfig":{"xp":{"base":35,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    'ec56aab7-6330-4dce-8687-f1a519b7c4d6',
    'download-the-emorya-app',
    'Download the Emorya app',
    'Download the Emorya app and confirm installation.',
    'app',
    40,
    'easy',
    'manual-review',
    'one-time',
    'free',
    1,
    FALSE,
    TRUE,
    '{"track":"starter","targetUrl":"https://example.com/download-app","unlockRules":{"all":[]},"submissionGuidance":{"evidence":["app install screenshot"]},"rewardConfig":{"xp":{"base":40,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    'd6f49297-0d44-49d4-a0f4-4f8da7fd59d7',
    'open-the-app-for-the-first-time',
    'Open the app for the first time',
    'Launch the Emorya app and enter your first active session.',
    'app',
    30,
    'easy',
    'link-visit',
    'one-time',
    'free',
    1,
    FALSE,
    TRUE,
    '{"track":"starter","targetUrl":"https://example.com/open-app","unlockRules":{"all":[]},"rewardConfig":{"xp":{"base":30,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    'bc875346-df7c-4e85-b5d6-67065be56c6b',
    'rate-emorya-on-the-app-store',
    'Rate Emorya on the App Store',
    'Leave a genuine rating for Emorya on the App Store after using the app.',
    'social',
    60,
    'easy',
    'manual-review',
    'one-time',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"social","targetUrl":"https://example.com/app-store-rating","unlockRules":{"all":[{"type":"min_level","value":3}]},"submissionGuidance":{"evidence":["rating confirmation screenshot"]},"rewardConfig":{"xp":{"base":60,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    '7f53ce74-c4da-4d4c-a968-d39b442a7e7e',
    'leave-your-first-emorya-review',
    'Leave your first Emorya review',
    'Write a real review of your Emorya experience and submit proof.',
    'social',
    120,
    'medium',
    'manual-review',
    'one-time',
    'free',
    4,
    FALSE,
    TRUE,
    '{"track":"social","platformLabel":"App Store","ctaLabel":"Open store listing","targetUrl":"https://apps.apple.com/app/example","helpUrl":"https://example.com/review-guide","proofType":"screenshot","proofInstructions":"Leave a genuine written review, then upload a review screenshot or paste the visible review proof for moderation.","unlockRules":{"all":[{"type":"min_level","value":4}]},"submissionGuidance":{"evidence":["review screenshot","review text excerpt"]},"rewardConfig":{"xp":{"base":120,"premiumMultiplierEligible":true},"tokenEffect":"none"},"previewConfig":{"label":"Review credibility quest"}}'::jsonb
  ),
  (
    '9d955d0c-a8cf-45d0-b5a2-e28f5de26468',
    'submit-your-referral-story',
    'Submit your referral story',
    'Write a short explanation of who you referred, why they were a fit for Emorya, and what happened next.',
    'referral',
    95,
    'medium',
    'text-submission',
    'monthly',
    'free',
    3,
    FALSE,
    TRUE,
    '{"track":"referral","platformLabel":"Referral","proofType":"text","proofInstructions":"Explain who you referred, why they were a strong fit, and whether they activated.","unlockRules":{"all":[{"type":"min_level","value":3}]},"rewardConfig":{"xp":{"base":95,"premiumMultiplierEligible":true},"tokenEffect":"none"},"previewConfig":{"label":"Referral story"}}'::jsonb
  ),
  (
    '86caa40f-3578-4e7b-9660-5a60d462f65f',
    'share-your-emorya-testimonial',
    'Share your Emorya testimonial',
    'Write a short testimonial about your Emorya experience, what has helped, and why you keep using it.',
    'social',
    110,
    'medium',
    'text-submission',
    'monthly',
    'free',
    4,
    FALSE,
    TRUE,
    '{"track":"social","platformLabel":"Testimonial","proofType":"text","proofInstructions":"Write a genuine short testimonial. Add an optional public reference link if you shared it elsewhere.","unlockRules":{"all":[{"type":"min_level","value":4}]},"rewardConfig":{"xp":{"base":110,"premiumMultiplierEligible":true},"tokenEffect":"none"},"previewConfig":{"label":"Testimonial trust signal"}}'::jsonb
  ),
  (
    'fd48b1a4-68e7-490b-9a98-18b3115edec4',
    'explain-your-calorie-to-emrs-journey',
    'Explain your calorie-to-EMRS journey',
    'Write a clear summary of how your calorie activity connects to EMRS progression and what that means to you.',
    'learn',
    125,
    'medium',
    'text-submission',
    'monthly',
    'free',
    5,
    FALSE,
    TRUE,
    '{"track":"learn","platformLabel":"EMRS journey","proofType":"text","proofInstructions":"Summarize how calorie conversion connects to EMRS and rewards in your own words.","unlockRules":{"all":[{"type":"min_level","value":5}]},"rewardConfig":{"xp":{"base":125,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":18}},"previewConfig":{"label":"Reward understanding"}}'::jsonb
  ),
  (
    'fe80b525-7453-40db-b224-53d2f39fc7db',
    'verify-zealy-campaign-task',
    'Verify Zealy campaign task',
    'Complete the linked Zealy task and submit the external reference for API verification.',
    'app',
    80,
    'medium',
    'api-check',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"campaign","platformLabel":"Zealy","ctaLabel":"Open Zealy task","targetUrl":"https://zealy.io/c/example/quest-board","proofType":"url","proofInstructions":"Complete the Zealy task, then submit the external reference URL or completion id for verification.","apiVerification":{"endpointUrl":"https://example.com/api/verify/zealy","method":"POST","failureMode":"pending-review"},"rewardConfig":{"xp":{"base":80,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":15}},"previewConfig":{"label":"Zealy API check"}}'::jsonb
  ),
  (
    'c7a9917c-02ad-46ef-94fd-6850c2a88647',
    'verify-galxe-campaign-credential',
    'Verify Galxe campaign credential',
    'Complete the linked Galxe credential step and submit the participation reference for verification.',
    'social',
    70,
    'medium',
    'api-check',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"campaign","platformLabel":"Galxe","ctaLabel":"Open Galxe campaign","targetUrl":"https://app.galxe.com/quest/example","proofType":"url","proofInstructions":"Complete the credential step, then submit the Galxe profile or participation reference for verification.","apiVerification":{"endpointUrl":"https://example.com/api/verify/galxe","method":"POST","failureMode":"pending-review"},"rewardConfig":{"xp":{"base":70,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":12}},"previewConfig":{"label":"Galxe credential check"}}'::jsonb
  ),
  (
    '1ec4b47a-905b-444a-a0c9-8021f5b7bda8',
    'create-an-emorya-progress-reel',
    'Create an Emorya progress reel',
    'Make a short-form video showing your Emorya progress or streak milestone.',
    'creative',
    220,
    'medium',
    'manual-review',
    'weekly',
    'free',
    6,
    FALSE,
    TRUE,
    '{"track":"creative","unlockRules":{"all":[{"type":"min_level","value":6}]},"submissionGuidance":{"evidence":["video link","cover screenshot"]},"rewardConfig":{"xp":{"base":220,"premiumMultiplierEligible":true},"tokenEffect":"none"}}'::jsonb
  ),
  (
    '1c31bf57-42b4-4788-8d0c-6a8dfb587205',
    'demo-link-visit-check',
    'Admin demo: Link visit check',
    'Open the linked admin demo destination to validate the link-visit lane.',
    'app',
    15,
    'easy',
    'link-visit',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"campaign","platformLabel":"Website","ctaLabel":"Open demo destination","targetUrl":"https://example.com/demo/link-visit","campaignPackId":"admin-verification-demo","campaignPackLabel":"Admin verification demo","previewConfig":{"label":"Link visit lane"}}'::jsonb
  ),
  (
    'b3bf5b0d-d3b5-44c7-bf57-1fcb3ef4c16a',
    'demo-manual-review-proof',
    'Admin demo: Manual review proof',
    'Submit a screenshot and note to validate the manual-review lane and task-block evidence capture.',
    'creative',
    40,
    'medium',
    'manual-review',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"creative","platformLabel":"Review queue","ctaLabel":"Open upload brief","targetUrl":"https://example.com/demo/manual-review","proofType":"file-upload","proofInstructions":"Upload one proof file and add a short reviewer note.","campaignPackId":"admin-verification-demo","campaignPackLabel":"Admin verification demo","taskBlocks":[{"id":"open-brief","label":"Open the demo brief","platformLabel":"Website","ctaLabel":"Open brief","targetUrl":"https://example.com/demo/manual-review","proofType":"link","proofInstructions":"Open the instructions before submitting.","required":true},{"id":"upload-proof","label":"Upload proof and context","description":"Attach a proof file and explain what you completed.","platformLabel":"Review queue","proofType":"file-upload","proofInstructions":"Upload a file and add a note for moderation.","required":true}],"previewConfig":{"label":"Manual review lane"}}'::jsonb
  ),
  (
    'c8688e5c-5631-4942-8942-bd7c52c61f5e',
    'demo-text-submission-brief',
    'Admin demo: Text submission brief',
    'Write a short response to validate the text-submission lane.',
    'learn',
    25,
    'easy',
    'text-submission',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"starter","platformLabel":"Written response","proofType":"text","proofInstructions":"Write a 2-3 sentence answer describing what this lane is good for.","campaignPackId":"admin-verification-demo","campaignPackLabel":"Admin verification demo","previewConfig":{"label":"Text submission lane"}}'::jsonb
  ),
  (
    'ca06bfa0-ed59-4c2a-83fc-d83e369b0283',
    'demo-quiz-readiness-check',
    'Admin demo: Quiz readiness check',
    'Answer the short quiz correctly to validate the quiz lane.',
    'learn',
    30,
    'easy',
    'quiz',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"quiz","totalQuestions":3,"passScore":2,"campaignPackId":"admin-verification-demo","campaignPackLabel":"Admin verification demo","previewConfig":{"label":"Quiz lane"}}'::jsonb
  ),
  (
    '82bc2777-cfc4-4264-9654-810bfe4abd4f',
    'demo-wallet-connection-check',
    'Admin demo: Wallet connection check',
    'Verify a linked wallet to validate the wallet-check lane.',
    'app',
    35,
    'easy',
    'wallet-check',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"wallet","platformLabel":"Wallet","proofInstructions":"Pick a linked wallet and submit it for verification.","walletCheckMode":"linked-wallet-ownership","campaignPackId":"admin-verification-demo","campaignPackLabel":"Admin verification demo","previewConfig":{"label":"Wallet-check lane"}}'::jsonb
  ),
  (
    '0f2612d6-1652-4d2b-84c9-6b8cdb0fd83f',
    'demo-api-verification-callback',
    'Admin demo: API verification callback',
    'Submit an external reference and resolve it later through the async callback lane.',
    'app',
    45,
    'medium',
    'api-check',
    'one-time',
    'free',
    1,
    FALSE,
    FALSE,
    '{"track":"campaign","platformLabel":"Webhook verifier","ctaLabel":"Open verifier guide","targetUrl":"https://example.com/demo/api-check","proofType":"url","proofInstructions":"Submit an external reference, then resolve it later through the callback endpoint.","apiVerification":{"endpointUrl":"https://example.com/api/verify/demo","method":"POST","failureMode":"pending-review","callbackToken":"demo-callback-token"},"campaignPackId":"admin-verification-demo","campaignPackLabel":"Admin verification demo","previewConfig":{"label":"API callback lane"}}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  xp_reward = EXCLUDED.xp_reward,
  difficulty = EXCLUDED.difficulty,
  verification_type = EXCLUDED.verification_type,
  recurrence = EXCLUDED.recurrence,
  required_tier = EXCLUDED.required_tier,
  required_level = EXCLUDED.required_level,
  is_premium_preview = EXCLUDED.is_premium_preview,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();

UPDATE quest_definitions
SET metadata = metadata || '{"questPortability":"emorya_only"}'::jsonb,
    updated_at = NOW()
WHERE slug IN (
  'create-emorya-account',
  'play-emoryan-adventure-game',
  'complete-daily-wheel-spin',
  'convert-your-first-calories',
  '500-in-24',
  'weekly-warrior',
  '14-day-calorie-streak',
  'convert-2000-calories-to-emrs',
  'emorya-marathon',
  'rate-emorya-on-the-app-store',
  'leave-your-first-emorya-review',
  'share-your-verified-progress-screenshot',
  'share-your-emorya-testimonial',
  'explain-your-calorie-to-emrs-journey'
);

UPDATE quest_definitions
SET metadata = jsonb_set(
      (metadata || '{"questPortability":"portable_adapt"}'::jsonb) - 'brandThemes',
      '{brandThemes}',
      '["emorya","xportal"]'::jsonb,
      true
    ),
    updated_at = NOW()
WHERE slug = 'connect-your-xportal-wallet';

UPDATE quest_definitions
SET metadata = metadata || '{"questPortability":"campaign_conditional"}'::jsonb,
    updated_at = NOW()
WHERE slug IN (
  'zealy-bridge-sprint',
  'galxe-migration-loop',
  'taskon-conversion-lane',
  'verify-zealy-campaign-task',
  'verify-galxe-campaign-credential'
);

INSERT INTO quest_definitions (
  id,
  slug,
  title,
  description,
  category,
  xp_reward,
  difficulty,
  verification_type,
  recurrence,
  required_tier,
  required_level,
  is_premium_preview,
  is_active,
  metadata
) VALUES
  (
    '8d45a988-c2f9-4ef2-ae76-0278d84517ee',
    'share-first-calorie-conversion-celebration',
    'Share your first calorie conversion celebration',
    'Share your first calorie-to-EMRS celebration moment once milestone sharing is live.',
    'social',
    140,
    'medium',
    'manual-review',
    'one-time',
    'free',
    3,
    FALSE,
    FALSE,
    '{"track":"social","platformLabel":"Milestone share","proofType":"url","proofInstructions":"Submit the public share URL once the milestone-share flow is live.","questPortability":"emorya_only","shareTrigger":"first_calorie_conversion","unlockRules":{"all":[{"type":"runtime_flag","value":"milestone_share_enabled"},{"type":"quest_completed","value":"convert-your-first-calories"}]},"previewConfig":{"label":"Milestone share placeholder"}}'::jsonb
  ),
  (
    '33d95da7-b7cb-4838-b24b-a65f8d636ad9',
    'share-your-7-day-streak-win',
    'Share your 7-day streak win',
    'Share your completed Weekly Warrior streak once milestone sharing is live.',
    'social',
    220,
    'medium',
    'manual-review',
    'monthly',
    'free',
    5,
    FALSE,
    FALSE,
    '{"track":"social","platformLabel":"Milestone share","proofType":"url","proofInstructions":"Submit the public share URL once the milestone-share flow is live.","questPortability":"emorya_only","shareTrigger":"weekly_warrior_complete","unlockRules":{"all":[{"type":"runtime_flag","value":"milestone_share_enabled"},{"type":"quest_completed","value":"weekly-warrior"}]},"previewConfig":{"label":"Weekly streak share"}}'::jsonb
  ),
  (
    'f626b825-bb4f-42bd-b5c3-80eb59371c0e',
    'share-your-referral-signup-win',
    'Share your referral signup win',
    'Share a verified referral signup moment once milestone sharing is live.',
    'social',
    160,
    'medium',
    'manual-review',
    'monthly',
    'free',
    3,
    FALSE,
    FALSE,
    '{"track":"referral","platformLabel":"Milestone share","proofType":"url","proofInstructions":"Submit the public share URL once the milestone-share flow is live.","questPortability":"portable_adapt","shareTrigger":"referral_signup","unlockRules":{"all":[{"type":"runtime_flag","value":"milestone_share_enabled"},{"type":"quest_completed","value":"send-your-first-referral-wave"}]},"previewConfig":{"label":"Referral win share"}}'::jsonb
  ),
  (
    'ad58f425-d60d-4df9-875b-7c93b6cadfa4',
    'share-your-premium-unlock',
    'Share your premium unlock',
    'Share your premium upgrade moment once milestone sharing is live.',
    'social',
    260,
    'medium',
    'manual-review',
    'one-time',
    'monthly',
    4,
    FALSE,
    FALSE,
    '{"track":"premium","platformLabel":"Milestone share","proofType":"url","proofInstructions":"Submit the public share URL once the milestone-share flow is live.","questPortability":"portable_adapt","shareTrigger":"premium_unlock","unlockRules":{"all":[{"type":"runtime_flag","value":"milestone_share_enabled"},{"type":"quest_completed","value":"upgrade-to-premium-monthly"}]},"previewConfig":{"label":"Premium unlock share"}}'::jsonb
  ),
  (
    '24820e34-e627-4979-90dc-d63c2714c077',
    'share-your-marathon-completion',
    'Share your marathon completion',
    'Share your Emorya Marathon completion once milestone sharing is live.',
    'social',
    420,
    'hard',
    'manual-review',
    'one-time',
    'free',
    8,
    FALSE,
    FALSE,
    '{"track":"ambassador","platformLabel":"Milestone share","proofType":"url","proofInstructions":"Submit the public share URL once the milestone-share flow is live.","questPortability":"emorya_only","shareTrigger":"marathon_complete","unlockRules":{"all":[{"type":"runtime_flag","value":"milestone_share_enabled"},{"type":"quest_completed","value":"emorya-marathon"}]},"previewConfig":{"label":"Marathon share"}}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  xp_reward = EXCLUDED.xp_reward,
  difficulty = EXCLUDED.difficulty,
  verification_type = EXCLUDED.verification_type,
  recurrence = EXCLUDED.recurrence,
  required_tier = EXCLUDED.required_tier,
  required_level = EXCLUDED.required_level,
  is_premium_preview = EXCLUDED.is_premium_preview,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();

INSERT INTO quest_completions (id, user_id, quest_id, status, submission_data, completed_at) VALUES
  (
    '2d5317b5-354c-4764-9007-ad26dc6bef26',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    '4cbda570-89a7-4c9d-bcdc-3e482ed02ae3',
    'approved',
    '{"score":5,"answersCorrect":5}'::jsonb,
    NOW() - INTERVAL '2 days'
  ),
  (
    '7745fe88-37c0-4114-9f79-b61c111f3771',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    'e62bc5b8-3280-4d18-b2fd-a1524c21b453',
    'pending',
    '{"platform":"Emorya App","contentUrl":"https://example.com/calorie-burn-summary","screenshotUrl":"https://example.com/proof.png","note":"Calorie burn target completed and converted to EMRS","submittedAt":"2026-03-12T09:00:00.000Z"}'::jsonb,
    NULL
  ),
  (
    '274d1bc4-abf1-4d59-bb23-432cbfcb9108',
    '2196480b-b0fc-4e15-8837-e1d02177c7ed',
    '76d48c0e-38b3-4087-8863-68d308ee60b8',
    'approved',
    '{"walletCheck":"stake-held-7-days"}'::jsonb,
    NOW() - INTERVAL '1 day'
  )
ON CONFLICT (user_id, quest_id) DO NOTHING;

INSERT INTO achievements (id, slug, name, description, category, condition) VALUES
  (
    '3105690b-c12b-4955-8f24-369953f3362c',
    'zealy-veteran',
    'Zealy Veteran',
    'Recognised warm traffic from a prior campaign journey.',
    'recognition',
    '{"source":"zealy"}'::jsonb
  ),
  (
    'd8d2c5c2-f553-4a78-aa29-e1c8162c66a6',
    'streak-machine',
    'Streak Machine',
    'Maintain a daily quest streak for 30 days.',
    'streak',
    '{"days":30}'::jsonb
  ),
  (
    'd66dfc8f-00b0-45d6-80f8-cfe481f672dc',
    'premium-champion',
    'Premium Champion',
    'Annual Premium badge with top-tier leaderboard prestige.',
    'subscription',
    '{"tier":"annual"}'::jsonb
  ),
  (
    '18e97076-e0c1-4446-a723-64f500cb4555',
    'quest-climber',
    'Quest Climber',
    'Finish five approved quests and prove the loop is sticking.',
    'quests',
    '{"approvedQuests":5}'::jsonb
  ),
  (
    'f8a5272b-d010-44a1-9635-1524f4b7e1d2',
    'referral-catalyst',
    'Referral Catalyst',
    'Bring in three new people with your code.',
    'referral',
    '{"invitedCount":3}'::jsonb
  ),
  (
    '1541ef42-e14d-4817-afb0-d0cf9174e421',
    'conversion-closer',
    'Conversion Closer',
    'Drive two invited users into a paid tier.',
    'referral',
    '{"convertedCount":2}'::jsonb
  ),
  (
    '7c1d67b8-c20e-42fc-9b7e-d0d987eb5f24',
    'level-ascendant',
    'Level Ascendant',
    'Reach level 10 and hold a meaningful presence on the board.',
    'progression',
    '{"level":10}'::jsonb
  ),
  (
    'c92b84d2-e9a9-4cb7-a22f-f3b02be029b3',
    'xp-collector',
    'XP Collector',
    'Accumulate 5,000 total XP across quests, referrals, and streak play.',
    'progression',
    '{"totalXp":5000}'::jsonb
  ),
  (
    'b944662a-f5d7-4d55-a942-1d03fe6bd6d0',
    'wallet-synced',
    'Wallet Synced',
    'Link a MultiversX wallet and bring on-chain identity into the account.',
    'wallet',
    '{"linkedWallets":1}'::jsonb
  ),
  (
    'db806fd0-f7dc-42ff-8f5a-0f13869e4b2e',
    'creator-signal',
    'Creator Signal',
    'Get two manual-review creator quests approved.',
    'creative',
    '{"manualReviewApprovals":2}'::jsonb
  ),
  (
    '1dc2f179-c55e-445d-b33d-389fca6a1593',
    'daily-ritual',
    'Daily Ritual',
    'Complete five approved daily quests.',
    'consistency',
    '{"dailyApprovals":5}'::jsonb
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO user_achievements (user_id, achievement_id, progress, earned_at) VALUES
  ('6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', '3105690b-c12b-4955-8f24-369953f3362c', 1, NOW() - INTERVAL '12 days'),
  ('6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'd8d2c5c2-f553-4a78-aa29-e1c8162c66a6', 0.47, NULL),
  ('6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'd66dfc8f-00b0-45d6-80f8-cfe481f672dc', 0, NULL)
ON CONFLICT (user_id, achievement_id) DO NOTHING;

INSERT INTO referrals (
  id,
  referrer_user_id,
  referee_user_id,
  referee_subscribed,
  signup_reward_xp,
  conversion_reward_xp,
  signup_rewarded_at,
  conversion_rewarded_at,
  created_at
) VALUES
  (
    '63b9d1aa-1303-4c3a-9f7d-0c79dc8f42a2',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    '8cc801df-004b-4e20-a5c1-cf5f0f1f642d',
    FALSE,
    40,
    0,
    NOW() - INTERVAL '16 days',
    NULL,
    NOW() - INTERVAL '16 days'
  ),
  (
    '64e0700d-5f73-4286-8f85-ef4c16c0cf62',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    '2b74bcd9-98e8-455a-bede-d1a5876775fd',
    TRUE,
    40,
    120,
    NOW() - INTERVAL '18 days',
    NOW() - INTERVAL '10 days',
    NOW() - INTERVAL '18 days'
  )
ON CONFLICT (referrer_user_id, referee_user_id) DO NOTHING;

INSERT INTO leaderboard_snapshots (id, user_id, period, xp, rank, snapshot_date) VALUES
  ('55730039-a930-421a-bea5-f02e7a0685f7', '2196480b-b0fc-4e15-8837-e1d02177c7ed', 'all-time', 37140, 1, CURRENT_DATE),
  ('14d3fb4c-1e8f-407f-b8e1-c4f0b96c4bb6', '9010db77-a008-4f24-ac2c-af801dca9a6b', 'all-time', 35520, 2, CURRENT_DATE),
  ('18ced7b2-9908-4fb2-aa02-0a04549d8c99', 'c657ad58-bf65-4def-8cab-5f2bd4a85dbf', 'all-time', 34100, 3, CURRENT_DATE),
  ('07c15333-4cda-47c1-bf4f-909bc95282f4', '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c', 'all-time', 4520, 34, CURRENT_DATE),
  ('d21b6ed0-765d-4a4f-997d-0550c3bef91f', '8cc801df-004b-4e20-a5c1-cf5f0f1f642d', 'all-time', 4485, 35, CURRENT_DATE),
  ('1ba52233-efec-4631-998e-b9f00b1f1176', '2b74bcd9-98e8-455a-bede-d1a5876775fd', 'all-time', 4440, 36, CURRENT_DATE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO activity_log (id, user_id, action_type, xp_earned, metadata, created_at) VALUES
  (
    'e2479df3-bc60-42c3-a53d-d2960d13efe6',
    '2196480b-b0fc-4e15-8837-e1d02177c7ed',
    'subscription_upgrade',
    0,
    '{"actor":"Lina","action":"earned Premium Champion","detail":"upgraded to Annual and unlocked 3 streak freezes","timeAgo":"2m ago"}'::jsonb,
    NOW() - INTERVAL '2 minutes'
  ),
  (
    'ba0fdc1a-4b14-4f7f-8147-384ddfef66d9',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    'daily_complete',
    25,
    '{"actor":"Oliver","action":"completed Daily Complete","detail":"finished 3 featured quests for 25 bonus XP","timeAgo":"11m ago"}'::jsonb,
    NOW() - INTERVAL '11 minutes'
  ),
  (
    '19335cc2-8d39-4954-a5f6-54bb8bcf7854',
    'c657ad58-bf65-4def-8cab-5f2bd4a85dbf',
    'ugc_submission',
    0,
    '{"actor":"Mia","action":"submitted a creator brief","detail":"waiting for review in Be Creative","timeAgo":"17m ago"}'::jsonb,
    NOW() - INTERVAL '17 minutes'
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO token_redemptions (
  id,
  user_id,
  asset,
  eligibility_points_spent,
  token_amount,
  status,
  source,
  metadata,
  created_at,
  settled_at,
  settled_by,
  receipt_reference,
  settlement_note
) VALUES
  (
    '62f3ce2a-5d0d-4c32-b1a0-1bdf40ba22b2',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    'EMR',
    120,
    6.0000,
    'settled',
    'xp-conversion',
    '{"note":"Weekly reward conversion","campaign":"direct"}'::jsonb,
    NOW() - INTERVAL '10 days',
    NOW() - INTERVAL '9 days',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    'EMR-PAYOUT-240305',
    'Paid manually during weekly reward reconciliation.'
  ),
  (
    '54f9ae95-60c6-44b8-81b2-a3917a65e145',
    '2196480b-b0fc-4e15-8837-e1d02177c7ed',
    'EMR',
    100,
    5.0000,
    'claimed',
    'xp-conversion',
    '{"note":"Awaiting payout","campaign":"galxe"}'::jsonb,
    NOW() - INTERVAL '2 days',
    NULL,
    NULL,
    NULL,
    NULL
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO moderation_notification_deliveries (
  id,
  channel,
  event_status,
  destination,
  title,
  detail,
  fingerprint,
  acknowledged_at,
  acknowledged_by,
  created_at
) VALUES
  (
    '1b73584d-f293-4389-ae23-4ce34b0c2f77',
    'inbox',
    'acknowledged',
    'Admin inbox',
    'Inbox escalation ready',
    '2 moderation alerts active. Oldest warning 360 min, stale threshold 1440 min.',
    md5('inbox|Admin inbox|Inbox escalation ready|queue breach acknowledged'),
    NOW() - INTERVAL '4 hours',
    '6f56c71e-6d79-4b18-bf43-d42d15eb0b8c',
    NOW() - INTERVAL '5 hours'
  ),
  (
    '0ce72af6-32da-4f66-aebd-49587b5f3a49',
    'slack',
    'sent',
    'https://hooks.slack.com/services/example/example/example',
    'Slack alert armed',
    'Slack delivery is configured for moderation SLA and backlog digests.',
    md5('slack|slack-alert-armed|queue breach'),
    NULL,
    NULL,
    NOW() - INTERVAL '90 minutes'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO economy_settings (
  id,
  is_active,
  published_brand_theme,
  payout_asset,
  payout_mode,
  redemption_enabled,
  settlement_processing_enabled,
  direct_reward_queue_enabled,
  settlement_notes_required,
  direct_rewards_enabled,
  direct_annual_referral_enabled,
  direct_premium_flash_enabled,
  direct_ambassador_enabled,
  differentiate_upstream_campaign_sources,
  minimum_eligibility_points,
  points_per_token,
  xp_multiplier_free,
  xp_multiplier_monthly,
  xp_multiplier_annual,
  token_multiplier_free,
  token_multiplier_monthly,
  token_multiplier_annual,
  referral_signup_base_xp,
  referral_monthly_conversion_base_xp,
  referral_annual_conversion_base_xp,
  annual_referral_direct_token_amount,
  campaign_alert_channels,
  campaign_overrides
) VALUES (
  'ce246eca-e256-487d-849c-769dbd5f366c',
  TRUE,
  'emorya',
  'EMR',
  'manual',
  FALSE,
  TRUE,
  TRUE,
  FALSE,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  FALSE,
  100,
  20,
  1.00,
  1.25,
  1.50,
  1.00,
  1.15,
  1.30,
  40,
  150,
  300,
  25.0000,
  '{"inboxEnabled": true, "webhookUrl": null, "emailRecipient": null, "slackWebhookUrl": null, "discordWebhookUrl": null}'::jsonb,
  '{
    "direct": {"signupBonusXp": 0, "monthlyConversionBonusXp": 0, "annualConversionBonusXp": 0, "annualDirectTokenBonus": 0, "questXpMultiplierBonus": 0, "eligibilityPointsMultiplierBonus": 0, "tokenYieldMultiplierBonus": 0, "minimumEligibilityPointsOffset": 0, "directTokenRewardBonus": 0, "weeklyTargetXpOffset": 0, "premiumUpsellBonusMultiplier": 0, "leaderboardMomentumBonus": 0},
    "zealy": {"signupBonusXp": 10, "monthlyConversionBonusXp": 20, "annualConversionBonusXp": 40, "annualDirectTokenBonus": 5, "questXpMultiplierBonus": 0.05, "eligibilityPointsMultiplierBonus": 0.10, "tokenYieldMultiplierBonus": 0.05, "minimumEligibilityPointsOffset": -10, "directTokenRewardBonus": 1, "weeklyTargetXpOffset": -15, "premiumUpsellBonusMultiplier": 0.08, "leaderboardMomentumBonus": 0.05},
    "galxe": {"signupBonusXp": 5, "monthlyConversionBonusXp": 30, "annualConversionBonusXp": 55, "annualDirectTokenBonus": 7, "questXpMultiplierBonus": 0.03, "eligibilityPointsMultiplierBonus": 0.12, "tokenYieldMultiplierBonus": 0.08, "minimumEligibilityPointsOffset": -5, "directTokenRewardBonus": 2, "weeklyTargetXpOffset": -10, "premiumUpsellBonusMultiplier": 0.10, "leaderboardMomentumBonus": 0.08},
    "taskon": {"signupBonusXp": 15, "monthlyConversionBonusXp": 25, "annualConversionBonusXp": 70, "annualDirectTokenBonus": 10, "questXpMultiplierBonus": 0.08, "eligibilityPointsMultiplierBonus": 0.15, "tokenYieldMultiplierBonus": 0.10, "minimumEligibilityPointsOffset": -15, "directTokenRewardBonus": 2, "weeklyTargetXpOffset": -20, "premiumUpsellBonusMultiplier": 0.12, "leaderboardMomentumBonus": 0.12}
  }'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  payout_asset = EXCLUDED.payout_asset,
  payout_mode = EXCLUDED.payout_mode,
  redemption_enabled = EXCLUDED.redemption_enabled,
  settlement_processing_enabled = EXCLUDED.settlement_processing_enabled,
  direct_reward_queue_enabled = EXCLUDED.direct_reward_queue_enabled,
  settlement_notes_required = EXCLUDED.settlement_notes_required,
  direct_rewards_enabled = EXCLUDED.direct_rewards_enabled,
  direct_annual_referral_enabled = EXCLUDED.direct_annual_referral_enabled,
  direct_premium_flash_enabled = EXCLUDED.direct_premium_flash_enabled,
  direct_ambassador_enabled = EXCLUDED.direct_ambassador_enabled,
  differentiate_upstream_campaign_sources = EXCLUDED.differentiate_upstream_campaign_sources,
  minimum_eligibility_points = EXCLUDED.minimum_eligibility_points,
  points_per_token = EXCLUDED.points_per_token,
  xp_multiplier_free = EXCLUDED.xp_multiplier_free,
  xp_multiplier_monthly = EXCLUDED.xp_multiplier_monthly,
  xp_multiplier_annual = EXCLUDED.xp_multiplier_annual,
  token_multiplier_free = EXCLUDED.token_multiplier_free,
  token_multiplier_monthly = EXCLUDED.token_multiplier_monthly,
  token_multiplier_annual = EXCLUDED.token_multiplier_annual,
  referral_signup_base_xp = EXCLUDED.referral_signup_base_xp,
  referral_monthly_conversion_base_xp = EXCLUDED.referral_monthly_conversion_base_xp,
  referral_annual_conversion_base_xp = EXCLUDED.referral_annual_conversion_base_xp,
  annual_referral_direct_token_amount = EXCLUDED.annual_referral_direct_token_amount,
  campaign_alert_channels = EXCLUDED.campaign_alert_channels,
  campaign_overrides = EXCLUDED.campaign_overrides,
  updated_at = NOW();

INSERT INTO reward_assets (
  id,
  asset_id,
  symbol,
  name,
  decimals,
  icon_url,
  issuer_name,
  is_active,
  is_partner_asset
) VALUES
  ('c79db59c-3210-4b7c-95d1-4a481923f701', 'EMR', 'EMR', 'Emorya Reward Token', 18, NULL, 'Emorya', TRUE, FALSE),
  ('7e1c4abd-40ac-4a9c-b829-a80ab6a6cf02', 'EGLD', 'EGLD', 'MultiversX eGold', 18, NULL, 'MultiversX', TRUE, FALSE),
  ('d2031fc4-df61-446f-90d9-9fd726d63e87', 'PARTNER', 'PARTNER', 'Partner Campaign Token', 18, NULL, 'Partner', TRUE, TRUE)
ON CONFLICT (id) DO UPDATE SET
  asset_id = EXCLUDED.asset_id,
  symbol = EXCLUDED.symbol,
  name = EXCLUDED.name,
  decimals = EXCLUDED.decimals,
  icon_url = EXCLUDED.icon_url,
  issuer_name = EXCLUDED.issuer_name,
  is_active = EXCLUDED.is_active,
  is_partner_asset = EXCLUDED.is_partner_asset,
  updated_at = NOW();

INSERT INTO reward_programs (
  id,
  slug,
  name,
  reward_asset_id,
  is_active,
  redemption_enabled,
  direct_rewards_enabled,
  referral_rewards_enabled,
  premium_rewards_enabled,
  ambassador_rewards_enabled,
  minimum_eligibility_points,
  points_per_token,
  notes
) VALUES
  ('fcae87e5-6f1b-4157-aa26-4c96cdfdd8d6', 'core-emr', 'Core Emorya XP Redemption', 'c79db59c-3210-4b7c-95d1-4a481923f701', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, 100, 20, 'Primary XP-to-token redemption program.'),
  ('4bec0c54-1f7d-4f74-b9cf-1e5b842d7fa4', 'egld-flash', 'EGLD Flash Rewards', '7e1c4abd-40ac-4a9c-b829-a80ab6a6cf02', TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, 120, 25, 'Use for premium flash days and limited reward spikes.'),
  ('1178ad8e-6d00-4ca4-96f0-838b9d4b35dd', 'partner-campaign', 'Partner Campaign Rewards', 'd2031fc4-df61-446f-90d9-9fd726d63e87', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, 100, 20, 'Template program for collaborative partner campaigns.')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  reward_asset_id = EXCLUDED.reward_asset_id,
  is_active = EXCLUDED.is_active,
  redemption_enabled = EXCLUDED.redemption_enabled,
  direct_rewards_enabled = EXCLUDED.direct_rewards_enabled,
  referral_rewards_enabled = EXCLUDED.referral_rewards_enabled,
  premium_rewards_enabled = EXCLUDED.premium_rewards_enabled,
  ambassador_rewards_enabled = EXCLUDED.ambassador_rewards_enabled,
  minimum_eligibility_points = EXCLUDED.minimum_eligibility_points,
  points_per_token = EXCLUDED.points_per_token,
  notes = EXCLUDED.notes,
  updated_at = NOW();

INSERT INTO quest_definition_templates (
  id,
  label,
  description,
  form_config,
  metadata,
  is_active
) VALUES
  (
    '9f71a1d8-90f7-490c-8e5d-c4ba1afb7232',
    'Starter ladder quest',
    'Low-friction onboarding step with XP-only progression.',
    '{"category":"app","difficulty":"easy","verificationType":"link-visit","recurrence":"one-time","requiredTier":"free","requiredLevel":1,"xpReward":25,"isPremiumPreview":false,"isActive":true}'::jsonb,
    '{"track":"starter","rewardConfig":{"xp":{"base":25,"premiumMultiplierEligible":true},"tokenEffect":"none"},"previewConfig":{"label":"Starter unlock"}}'::jsonb,
    TRUE
  ),
  (
    '0bc190f7-c0e8-4377-a5f9-c6bf9203069c',
    'Partner token flash quest',
    'Annual or premium spike quest with direct token payout and program mapping.',
    '{"category":"limited","difficulty":"hard","verificationType":"manual-review","recurrence":"weekly","requiredTier":"annual","requiredLevel":5,"xpReward":180,"isPremiumPreview":false,"isActive":true}'::jsonb,
    '{"track":"premium","rewardProgramId":"4bec0c54-1f7d-4f74-b9cf-1e5b842d7fa4","rewardConfig":{"xp":{"base":180,"premiumMultiplierEligible":true},"tokenEffect":"direct_token_reward","directTokenReward":{"asset":"EGLD","amount":20,"requiresWallet":true}},"unlockRules":{"all":[{"type":"subscription_tier","value":"annual"}]},"previewConfig":{"label":"Partner flash payout"}}'::jsonb,
    TRUE
  ),
  (
    '3926b1e8-657b-4afd-a8c8-f686b7b4a7a2',
    'Wallet growth milestone',
    'Eligibility-point quest mapped to wallet-linked progression.',
    '{"category":"staking","difficulty":"medium","verificationType":"wallet-check","recurrence":"weekly","requiredTier":"free","requiredLevel":3,"xpReward":70,"isPremiumPreview":false,"isActive":true}'::jsonb,
    '{"track":"wallet","rewardProgramId":"fcae87e5-6f1b-4157-aa26-4c96cdfdd8d6","rewardConfig":{"xp":{"base":70,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":15}},"unlockRules":{"all":[{"type":"wallet_linked","value":true}]},"previewConfig":{"label":"Wallet lane"}}'::jsonb,
    TRUE
  ),
  (
    'db2c4bdb-ae54-4ab0-98f8-0d93b7f899f1',
    'Zealy bridge quest',
    'Live Zealy bridge step that turns campaign momentum into wallet-linked Emorya progress.',
    '{"category":"app","difficulty":"medium","verificationType":"link-visit","recurrence":"one-time","requiredTier":"free","requiredLevel":1,"xpReward":85,"isPremiumPreview":false,"isActive":true}'::jsonb,
    '{"track":"campaign","rewardProgramId":"fcae87e5-6f1b-4157-aa26-4c96cdfdd8d6","targetUrl":"https://example.com/zealy-bridge","campaignTemplateKind":"bridge","campaignAttributionSource":"zealy","campaignExperienceLane":"zealy","rewardConfig":{"xp":{"base":85,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":18}},"unlockRules":{"all":[{"type":"campaign_source","value":"zealy"}]},"previewConfig":{"label":"Zealy bridge"}}'::jsonb,
    TRUE
  ),
  (
    'dbf543ea-4e51-4868-a552-0e8bc44dbd5a',
    'Galxe feeder quest',
    'External discovery quest that captures Galxe users and hands them into the Zealy bridge.',
    '{"category":"social","difficulty":"easy","verificationType":"link-visit","recurrence":"one-time","requiredTier":"free","requiredLevel":1,"xpReward":55,"isPremiumPreview":false,"isActive":true}'::jsonb,
    '{"track":"campaign","rewardProgramId":"fcae87e5-6f1b-4157-aa26-4c96cdfdd8d6","targetUrl":"https://example.com/galxe-bridge","campaignTemplateKind":"feeder","campaignAttributionSource":"galxe","campaignExperienceLane":"zealy","requiresUpstreamDifferentiation":false,"rewardConfig":{"xp":{"base":55,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":10}},"unlockRules":{"all":[{"type":"campaign_source","value":"galxe"}]},"previewConfig":{"label":"Galxe to Zealy feeder"}}'::jsonb,
    TRUE
  ),
  (
    '0de0c54c-18be-44b2-a019-f83c2281450f',
    'TaskOn feeder quest',
    'Task-completion handoff quest that moves TaskOn users into the Zealy bridge path.',
    '{"category":"app","difficulty":"medium","verificationType":"link-visit","recurrence":"one-time","requiredTier":"free","requiredLevel":1,"xpReward":60,"isPremiumPreview":false,"isActive":true}'::jsonb,
    '{"track":"campaign","rewardProgramId":"fcae87e5-6f1b-4157-aa26-4c96cdfdd8d6","targetUrl":"https://example.com/taskon-bridge","campaignTemplateKind":"feeder","campaignAttributionSource":"taskon","campaignExperienceLane":"zealy","requiresUpstreamDifferentiation":false,"rewardConfig":{"xp":{"base":60,"premiumMultiplierEligible":true},"tokenEffect":"eligibility_progress","tokenEligibility":{"progressPoints":12}},"unlockRules":{"all":[{"type":"campaign_source","value":"taskon"}]},"previewConfig":{"label":"TaskOn to Zealy feeder"}}'::jsonb,
    TRUE
  )
ON CONFLICT (label) DO UPDATE SET
  description = EXCLUDED.description,
  form_config = EXCLUDED.form_config,
  metadata = EXCLUDED.metadata,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

UPDATE token_redemptions
SET reward_asset_id = CASE asset
      WHEN 'EMR' THEN 'c79db59c-3210-4b7c-95d1-4a481923f701'::uuid
      WHEN 'EGLD' THEN '7e1c4abd-40ac-4a9c-b829-a80ab6a6cf02'::uuid
      ELSE 'd2031fc4-df61-446f-90d9-9fd726d63e87'::uuid
    END,
    reward_program_id = CASE asset
      WHEN 'EGLD' THEN '4bec0c54-1f7d-4f74-b9cf-1e5b842d7fa4'::uuid
      WHEN 'PARTNER' THEN '1178ad8e-6d00-4ca4-96f0-838b9d4b35dd'::uuid
      ELSE 'fcae87e5-6f1b-4157-aa26-4c96cdfdd8d6'::uuid
    END;
